### ISSUE TITLE
WEBP 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb2021_base#105]
We should investigate the status of the WEBP solutions and see if it makes sense for us going forward.  

Will need an ADR for this technical decision either way.

**Comment by jnicholCU** [comment]
@jcsparks I'm unsure of what our browser support policy is but it looks like WebP isn't supported for IE11 or versions of Safari before Big Sur. https://caniuse.com/webp 

I think the Safari support is more of the concern as I know lots of people still use Catalina and earlier, Catalina being the most popular version by far. https://www.statista.com/statistics/944559/worldwide-macos-version-market-share/
(Note that for whatever reason Apple has been reporting Big Sur as Catalina so it's hard to get a proper headcount)

It also looks like some other users have been running into this issue with wrapping WebP's in <picture> and still being able to have them be responsive properly. I don't think this should effect us but could be good to look through. https://www.drupal.org/project/drupal/issues/3213491 

The big modules I've found that are recommended for WebP are both pretty out of date (a year or more) so I'll need to keep searching if this is something we're wanting to do still.
