### ISSUE TITLE
Content Grid Block

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#106]
The content grid block's purpose was to allow users a way to create some different styles of column and row layouts of minimal information: A title, an image, and some text.

![image](https://user-images.githubusercontent.com/349713/144925804-608b96cf-2a45-43b8-82e0-d2ffc2e57db8.png)

Depending on the type of display you choose, you can also pick the number of columns you want the information displayed in.

I was thinking on way we could do this would be to create a "card" paragraph type which could only be added to a "grid container" paragraph type.  The container would have the display options and would then format the card content based on those values.

**Comment by jcsparks** [comment]
Merged in
