### ISSUE TITLE
Expandable Block

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#110]
The expandable block displays content as tabs/accordions.  Users should be able to select which of these they want to use, however, tabs should collapse to an accordion display on a mobile device.

The content of tabs should accept other paragraphs types, such as text, events, etc.

**Comment by jnicholCU** [comment]
Current demo version in Web Express
https://www.colorado.edu/demos/web-express/add-bundles/expandable-block
