### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#111]
A slider contains slides that allow the user to swipe left or right to view additional slides.

![image](https://user-images.githubusercontent.com/349713/144929040-5147bdc0-bb8c-4d7a-abce-6180f54fa040.png)

**Slide Contents**
Slide content contains an image, a title, some text, and a link.  

**Slide Images**
Sliders should have some image size options, such as a widescreen (16x9) size, regular (3x2) size, ultra wide (14x5) as well as using the original proportions of whatever has been uploaded.

**Slide Navigation**
- Sliders should be touch enabled to work with mobile devices.
- Slider should include previous/next links.
- Sliders should contain a dot navigation indicating how many sliders are in the slider and what slide is currently being shown.

**Comment by jnicholCU** [comment]
Current slider demo in web express
https://www.colorado.edu/demos/web-express/web-express-core/core-blocks/slider-block
