### ISSUE TITLE
Article Content Alignment

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#118]
Article content, regardless of which paragraph type it is, should all be aligned.  The image below shows that the hero type doesn't align with the two article content paragraph types.

![image](https://user-images.githubusercontent.com/349713/145876951-5e4c347c-a241-4a93-8d1b-48f266b7b672.png)

**Comment by jnicholCU** [comment]
After doing some testing on this I've found the alignment issue is only a problem in the site editor mode. 
We won't need to do a refactor of breaking the hero out of the container to fix the issue. I'll work on the CSS fix for editor mode.
