### ISSUE TITLE
Content Grid Image Styles

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#141]
Content grids have 2 image styles options that apply to every image in a grid - a square or a horizontal 2:1 aspect ratio.  Vertical images use too much space, particularly on a mobile device.

**Comment by jnicholCU** [comment]
@kevincrafts for this, do users upload two photos that get used or do they have a select option for square/horizontal?
Would you be able to provide screenshots of how this looks currently?
