### ISSUE TITLE
Quick edit functionality is weird and confusing

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#142]
Our users have been used to the contextual links to allow them to edit a specific piece of content and I think the quick edit functionality will confuse them, because it doesn't let them edit in the way they are used to.

For example, the quick edit on a content grid doesn't actually edit anything:

![image](https://user-images.githubusercontent.com/349713/153911205-652b8545-590d-4f33-9a5b-ede830601b00.png)

And then using the edit link only allows you to edit the image, not the grid or even that particular cell.

**Comment by jnicholCU** [comment]
Ran into a known issue where if you quick edit content once on a page it then disables all the quick edit buttons after. Looking for a fix on this now.

**Comment by jnicholCU** [comment]
We have decided to disable quick edit since it has been moved out of core for a11y reasons.
<img width="505" alt="image" src="https://user-images.githubusercontent.com/94021017/156653845-13a0471d-db74-466d-8d92-52e6b0c62add.png">
