### ISSUE TITLE
Social Media Block from Social Media Menu links

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb2021_base#146]
We should add an option to the Social Menu Paragraph to allow users to utilize the existing social media menu for the site. 

We should be able to do this with this : 
https://git.drupalcode.org/project/twig_tweak/-/blob/3.x/docs/cheat-sheet.md#drupal-menu

**Comment by jnicholCU** [comment]
Code for this issue was tested and merged in.
