### ISSUE TITLE
WYSIWYG Image Captions

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#147]
Editors need the ability to add a visible caption to an image. The caption may contain html such as links, italics, bold, etc.  The caption may need to be added to an image that is floated left or right.

![image](https://user-images.githubusercontent.com/349713/154373938-e2b06a02-d19f-4486-a1d8-1b3114ea945c.png)

**Comment by jcsparks** [comment]
We should talk a little about this one, but I suspect the best way to handle this is to extend the Media Image entity type to include an abstract field that is plain text.  That will give the users the option to add a caption to any and all images.  We can then overload the default field--media-image template to look for the captions and add it if present.
