### ISSUE TITLE
Photo Gallery

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#148]
Editors need the ability to add images to a page as a photo gallery.  Rather than do this as a content type like we have in the past, I think a gallery paragraph type that would display thumbnails in a grid would work fine. Images should have a Lightbox functionality which would also show image captions.

https://www.colorado.edu/today/week-photos-reconnecting-person

![image](https://user-images.githubusercontent.com/349713/154374435-a3056a46-e778-47ad-93d5-451906edb89c.png)

**Comment by jnicholCU** [comment]
https://www.colorado.edu/demos/web-express/add-bundles/photo-gallery

**Comment by jnicholCU** [comment]
https://websupport.colorado.edu/article/351-photo-gallery

**Comment by jnicholCU** [comment]
Closed in PR #169
