### ISSUE TITLE
Accordion Link Colors

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#149]
The colors for the accordion links look a little muted and I'm concerned they won't meet the proper contrast ratio for accessibility.
![image](https://user-images.githubusercontent.com/349713/154376478-bdf84c4e-a6fe-42b3-997b-2c9b492ffd14.png)

**Comment by jcsparks** [comment]
Oh wow, that's ironic.  We tried to copy what was in Express and the only way we could get the color to match was with an opacity.  Josh and I thought it was unlikely that this would meet WCAG AA as well but this looked the closest to the example we were trying to copy from Express.  Happy to lose the opacity here and get it up to at least 4.5 contrast.
