### ISSUE TITLE
RSS Block

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#158]
The RSS block shows the linked titles from an RSS feed.  The number of items shown(1-10) can be chosen by the editor. Below the items, there is a link to feed.

Demo: https://www.colorado.edu/demos/web-express/add-bundles/rss-feed-block

**Comment by jnicholCU** [comment]
The current Aggregator Module in Drupal 8 and 9 has been deprecated as of Drupal 9.4.
It is going to be removed in 9.5/10.0 
Going to need to find a solution that isn't a part of core.

**Comment by jnicholCU** [comment]
Fascinatingly it seems like you can only reference and use Aggregator Lists using the layout builder. Outside of this the Aggregator makes a separate page with the RSS feed on it. So it might be best to wait and add this in Tiamat. It is super simple to turn on and create the feeds then place with the layout builder. If we want this to be a block/paragraph instead it will take a little more work. Will discuss in next project management.
