### ISSUE TITLE
How do we export and import content schemas? 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb2021_base#16]
We'e done this with Features in the past.  Is this still the correct way to do this going forward? 

Is it possible that the configuration management tools have matured to the point that they can deal with page schemas now?

**Comment by AlanBCole** [comment]
Is this the assumed workflow for what is described in this issue?

1. Create a "page schema" -> create a content type in drupal's UI
	export it using tools available
    - core's included tooling
    - features module
    - other tools
2. Import it into a different site (same steps as 2.)

**Comment by jcsparks** [comment]
The workflow will be defined by the solution that we settle on.  I think this ticket is really more asking the question, "is there a better solution for this now than Features? (i.e. the solution that we've used in the past to accomplish this process)"

**Comment by jcsparks** [comment]
Features is working still.  We've successfully exported/imported content types using it to create modules.   Seems that this is still the way to go.
