### ISSUE TITLE
All Blocks need Titles

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#201]
All blocks/paragraph types should have the option of adding a title. Currently Text Blocks are the only ones that have this.

For example, this Events Calendar paragraph doesn't have the ability to add something like "Upcoming Events" to it.

![image](https://user-images.githubusercontent.com/349713/166746936-26064044-9e05-4875-9730-653597f723fe.png)

**Comment by jnicholCU** [comment]
One of the ways this is potentially solved is in layout builder. Each block that gets added has a required title section that can be displayed if selected. 
I'm not sure if that negates the need for title sections on all of our paragraphs.

**Comment by jcsparks** [comment]
Now that we've moved to Layout Builder this is no longer an issue.
