### ISSUE TITLE
Default Homepage

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#202]
All sites, when installed, should have a basic page created and set to the default homepage, instead of getting this current message:
![image](https://user-images.githubusercontent.com/349713/166747758-21f6021b-653b-49d3-93b8-bce240a3f412.png)

**Comment by jcsparks** [comment]
May need the default content module to solve this.  Will also improve automated testing by not generating a 404 immediately after installation.

**Comment by jcsparks** [comment]
Added in PR for template and profile (issue/202 on each) to include the new custom default content module that creates to the homepage to the project template and install profile.

**Comment by jcsparks** [comment]
New custom module to create a default homepage and set.  Added to composer list and install via profile.
