### ISSUE TITLE
Edit Site Info Block

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb2021_base#222]
The permissions granularity in Drupal doesn't allow us to give Site Owners the ability to edit the Site Info custom block content without giving the ability to modify the block layout.  

Two potential solutions : 

1. (Harder) Extend the permissions system to provide the necessary granularity to edit content in blocks without being able to move blocks around inside of the block layout
2. (Easier) Create a new admin control panel with a webform that will allow Site Owners to fill out the content necessary to populate the site info block that is already placed in the correct region.  

I suspect we will need this pattern for other administrative functions (e.g. giving users the ability to change theme settings without giving them the ability to change the theme in use).

**Comment by jcsparks** [comment]
https://www.drupal.org/docs/creating-custom-modules/creating-custom-blocks

**Comment by timurtripp** [comment]
Solution 2 was completed and is in the CU Boulder Site Configuration module, closing issue
