### ISSUE TITLE
Slider controls in above body block content area 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb2021_base#40]
The slider controls for a slider paragraph added into the above body block content area don't seem to work.  The controls do seem to work when the slider is placed above the content area but inside maybe not.  

See : http://cuw-dev01.colorado.edu/node/5

**Comment by brookestevens** [comment]
Bug was due to the title field having a value for the slider. When the title field is added, it messes up bootstrap causing it not to know what slide the slider is on. I removed the field since the title doesn't appear to be rendered on any of the sliders.
