### ISSUE TITLE
Bootstrap or other foundation layout framework

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb2021_base#5]
Bootstrap 5 is out.  Express used a subset of a previous version of Bootstrap.  We should evaluate using Bootstrap 5 and determine if it still makes sense to pull out a subset of the framework to integrate with our code for optimization reasons or just add the full library for ease of update/maintenance.

**Comment by brookestevens** [comment]
I think we should use a CSS framework to speed up development. I looked at Bootstrap 5 and it seems to perform just as well as 4. It's smaller in size than 4 and has no jQuery dependency. I think 5 is a good foundation and we can extend it using SCSS.  Tailwind CSS requires npm and a build process. Bulma and Pure CSS are quite similar to Bootstrap, but I haven't used them before. My personal preference is to just stick with Bootstrap. Also, most CSS frameworks require the use of a preprocessor to extend or customize them. Depending on how many customizations we need, we will have to use a preprocessor.

**Comment by jcsparks** [comment]
Great!  Good analysis Brooke.  I'm comfortable with Bootstrap 5, sounds like it's a good foundation for us.  Want to write up an ADR doc and start replacing 4 with 5 in the theme then?
