### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb2021_base#7]
We've used jQuery in the past.  It looks like Bootstrap no longer has this as a requirement.  We need to evaluate if there is a JS framework that we want to have built into the base theme.  If so does it make sense to stay with jQuery or perhaps it makes more sense to embrace something more modern like Vue.

**Comment by brookestevens** [comment]
As of now, I don't think using a JS framework is necessary. Twig is already pretty good and most of the web content is just read-only. JS frameworks are good for complex two-way data flow, which our sites don't really have. I think that Vue could be very useful in the future, but isn't needed for the base theme.

**Comment by jcsparks** [comment]
Great, I'm comfortable with vanilla JS as well.  I like the heuristic of only including Vue (or another JS platform) when we get to the point of needing two-way data integrations.  

Can you write up an ADR doc for this and we'll get it included as a decision point.
