### ISSUE TITLE
Remove logo option from theme settings

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb2021_base#75]
This is something we'll probably never use, so we shouldn't expose it to our users that might be pretty excited for a feature we'll never implement.

**Comment by jcsparks** [comment]
@kevincrafts we weren't intending to allow end users to be able to edit the theme settings.  Do you think there are things in the theme setting that they will need to be able to edit in general?

**Comment by TeddyBearX** [comment]
#74 resolves this. The default theme settings won't be exposed to users, instead there will be a separate configuration form with the specific theme settings we do want to expose.
