### ISSUE TITLE
Person Content Type

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb2021_base#9]
Need a Person content type schema definition and integration with https://schema.org/Person

**Comment by cathysnider** [comment]
Notes on Person Content type: 

Person Content Type uses the module 'auto_entitylabel' to combine fields 'First Name' and 'Last Name' to be the node title. 

Fields:

**Comment by jcsparks** [comment]
We won't need that module in D9 -- the theming engine for D9 is way more flexible in laying out content properly. 

Good job with the table though, that's a great start for what we're looking for.

**Comment by AlanBCole** [comment]
Would it be good to have one or more of the Filter1-3 term reference fields be associated with our likely use of the Permissions by Term module? Or maybe a separate field for that use?

**Comment by cathysnider** [comment]
@AlanBCole  Interesting idea. It would involve tying a Person node to a site User, though, wouldn't it? Which I don't think there's much demand for.
